### ISSUE TITLE
ClassNotFoundException magellan.PointUDT with PySpark

### ISSUE THREAD

**Issue by stevebuckingham** [harsha2010/magellan#105]
I'm using Spark 2.1, Spark and harsha2010:magellan:1.0.4-s_2.11

When attempting to run this sample code I get a ClassNotFoundException magellan.PointUDT exception:

**Initiate PySpark with Magellan**

pyspark --packages harsha2010:magellan:1.0.4-s_2.11

**PySpark Code**

from magellan.types import Point, Polygon
from pyspark.sql import Row, SQLContext

sq = SQLContext(sc)

PointRecord = Row("id", "point")

points = sc.parallelize([
  (0, Point(-1.0, -1.0)),
  (1, Point(-1.0, 1.0)),
  (2, Point(1.0, -1.0))])\
.map(lambda x: PointRecord(*x))

out = sq.createDataFrame(points)

out.show(1)

**Exception**

The exception comes at the point of createDataFrame.

: java.lang.ClassNotFoundException: magellan.PointUDT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:229)
	at org.apache.spark.sql.types.DataType$.parseDataType(DataType.scala:158)
	at org.apache.spark.sql.types.DataType$.org$apache$spark$sql$types$DataType$$parseStructField(DataType.scala:175)
	at org.apache.spark.sql.types.DataType$$anonfun$parseDataType$1.apply(DataType.scala:150)
	at org.apache.spark.sql.types.DataType$$anonfun$parseDataType$1.apply(DataType.scala:150)
	at scala.collection.immutable.List.map(List.scala:277)
	at org.apache.spark.sql.types.DataType$.parseDataType(DataType.scala:150)
	at org.apache.spark.sql.types.DataType$.fromJson(DataType.scala:104)
	at org.apache.spark.sql.SparkSession.applySchemaToPythonRDD(SparkSession.scala:690)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lagerspetz** [comment]
Hi, this is the same issue as this: 
https://github.com/harsha2010/magellan/issues/78
Please check my answer and see if you can get a bit further with that.

**Comment by stevebuckingham** [comment]
@lagerspetz OK - I've now got PointUDT working locally in a PySpark dataframe and will try other types. If you look at the Scala code it is now expecting x-min, x-max, y-min, y-max, as well as x and y for a point (but they are just set to x and y).

**Comment by lagerspetz** [comment]
Cool, you can probably submit a PR here, or give me some code and I can do it as well, once it works.

**Comment by stevebuckingham** [comment]
@lagerspetz For now I've forked it - I haven't had a chance to test my changes extensively yet but I believe Polygon, Point and PolyLine all work. If you want to try the fork it is here: https://github.com/stevebuckingham/magellan

**Comment by sto-nith** [comment]
Hi,

Did anyone get any resolution to this issue yet? I am also facing the same error:

SPARK: 2.1.1
MAGELLAN: 1.0.4-s_2.11

from pyspark import SparkConf,SparkContext
from pyspark.sql import SparkSession
from magellan.types import Point, Polygon
from pyspark.sql import Row, SQLContext
from pyspark.sql.functions import *
from pyspark.sql.types import StringType, DoubleType

conf = SparkConf().setAppName('dataEnhancement')
sc = SparkContext(conf=conf)
spark = SparkSession(sc)
#sc.setLogLevel('ERROR')
#sqlContext = HiveContext(sc)

PointRecord = Row('tripId', 'timestamp', 'point')

uberRidesDf = (
    sc
    .textFile('/home/saurabh/Downloads/uber-rides.tsv')
    .map(lambda x: x.split('\t'))
    .map(lambda x: (x[0], x[1], Point(float(x[3]), float(x[2]))))
    .map(lambda x: PointRecord(x[0], x[1], x[2]))
    )

uberRidesDf2 = (
    uberRidesDf
    .toDF()
    .cache()
    )

While converting from RDD to DF, it is throwing the error:

                   java.lang.ClassNotFoundException: magellan.PointUDT

Is there any resolution/workaround to this issue?
