### ISSUE TITLE
ShapefileReader recordNumber requirement failed

### ISSUE THREAD

**Issue by renkeji** [harsha2010/magellan#148]
New to shapefile, trying to load a shapefile to spark, and getting this error:
```
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:212)
	at magellan.mapreduce.ShapefileReader.nextKeyValue(ShapefileReader.scala:47)
	at org.apache.spark.rdd.NewHadoopRDD$$anon$1.hasNext(NewHadoopRDD.scala:199)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:39)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:149)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
The file I used to test can be loaded to qgis2 though, which means it should be a valid one.

**Comment by harsha2010** [comment]
Can you attach the shape file ?

**Comment by renkeji** [comment]
@harsha2010 Thanks for the reply, I am not sure I can attach the shapefile in github since it may be company confidential, I will check with my manager.

**Comment by renkeji** [comment]
@harsha2010 I have attached the files here, please find the .shp, .dbf files in the zip file.
[BoardOfEducTrustees.zip](https://github.com/harsha2010/magellan/files/1226764/BoardOfEducTrustees.zip)

**Comment by Charmatzis** [comment]
@renkeji the zip file is empty.
please, also include the qpj, prj, shx files.

**Comment by renkeji** [comment]
@Charmatzis I have re-attached the zip file which contains the all the files I have(there is no .qpj file though).

[BoardOfEducTrustees.zip](https://github.com/harsha2010/magellan/files/1227315/BoardOfEducTrustees.zip)

**Comment by harsha2010** [comment]
bin/spark-shell --packages harsha2010:magellan:1.0.5-s_2.11
val df = spark.read.format("magellan").load(s"$path")
df.show()

+-----+--------+--------------------+--------------------+-----+
|point|polyline|             polygon|            metadata|valid|
+-----+--------+--------------------+--------------------+-----+
| null|    null|magellan.Polygon@...|Map(SHAPE_STAr ->...| true|
| null|    null|magellan.Polygon@...|Map(OBJECTID ->  ...| true|
| null|    null|magellan.Polygon@...|Map(OBJECTID ->  ...| true|
| null|    null|magellan.Polygon@...|Map(Brd_Trust -> ...| true|
| null|    null|magellan.Polygon@...|Map(SHAPE_STLe ->...| true|
| null|    null|magellan.Polygon@...|Map(SHAPE_STAr ->...| true|
| null|    null|magellan.Polygon@...|Map(SHAPE_STLe ->...| true|
+-----+--------+--------------------+--------------------+-----+

 df.count()
res1: Long = 7

What is not working? Can you write down the actual code and instructions to reproduce the issue?

**Comment by renkeji** [comment]
@harsha2010 verified again, it works, I am closing this issue, thanks for checking for me.
