### ISSUE TITLE
ClassNotFoundException: magellan.PointUDT

### ISSUE THREAD

**Issue by denadai2** [harsha2010/magellan#78]
With Spark 1.4.1 and magellan 1.0.3, when I do

    prova = udf(lambda x,y: Point(x,y), Point())

I have

    java.lang.ClassNotFoundException: magellan.PointUDT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.apache.spark.sql.types.DataType$.parseDataType(DataType.scala:225)
	at org.apache.spark.sql.types.DataType$.fromJson(DataType.scala:166)
	at org.apache.spark.sql.SQLContext.parseDataType(SQLContext.scala:988)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)

Is this a bug?

**Comment by lagerspetz** [comment]
Hi, I don't understand enough about the Spark python bindings yet, but this looks like to be the cause:
https://github.com/harsha2010/magellan/blob/master/python/magellan/types.py#L72
The type magellan.PointUDT really does not exist, since it's now org.apache.spark.sql.types.PointUDT .

**Comment by lagerspetz** [comment]
Detailed instructions to test this change to the Python side:
`git clone https://github.com/lagerspetz/magellan.git`
(This already includes the change)
```
cd magellan
sbt compile publish-local
cd python
zip -9r pymagellan.zip magellan
cd /to/your/spark-2.1.0-folder
./bin/pyspark --jars $HOME/.ivy2/local/harsha2010/magellan_2.11/1.0.5-SNAPSHOT/jars/magellan_2.11.jar --py-files /path/to/magellan/python/pymagellan.zip
```
